<html>
    <body>
        
    <video id="video"  src="media/video/FallColorofNorthGeorgia.mp4" autoplay loop muted>
  
  Your browser does not support the video tag.
</video>

<div class="opacity"></div>


<div class="content content-about">
    <div class="sound">
        <img id="speaker" src="media/images/icon/speakerOff.png" alt="speaker">
    </div>
    <h2 class="title">Tours</h2>

    <div class="tours">
        <h3 class="tour-title">choose the duration of the trip<br> that best suits you  </h3>
        <div class="tour-container">
            <div class="tour-duration">
                <p class="duration">1<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">2<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">3<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">1<br>Week</p>
            </div>
            <div class="tour-duration">
                <p class="duration">Custom</p>
            </div>
        </div>
    </div>

    <div class="choose-tour">
        <div class="choose-duration">
            <div class="back duration-circle">
                <p class="back-p">&#9664;</p>
            </div>
            <div class="duration-number duration-circle">
                <p class="duration-number-p">
                    Choose <br> Number  <br>
                    <span id="duration-number-arrow">&#9660</span>
                    
                </p>
            </div>
            <div class="duration-day duration-circle">
                <p class="duration-day-p">
                    <span id="duration-day-span">Day</span> <br>
                    <span class="week-top">Week</span><br>
                   
                </p>
            </div>
            <div class="go duration-circle">
                <p class="duration-circle-p">
                    GO
                </p>
            </div>
            <div class="numbers">
                <span class="numbers-number">1</span>
                <span class="numbers-number">2</span>
                <span class="numbers-number">3</span>
                <span class="numbers-number">4</span>
                <span class="numbers-number">5</span>
                <span class="numbers-number">6</span>
                <span class="numbers-number">7</span>
            </div>
        </div>

        <div class="tour-main">
            <div class="map">
                <img id="map" src="media/images/map.png" alt="map" usemap="#image-map">
                <!-- Image Map Generated by http://www.image-map.net/ -->


                <map name="image-map">
    <area target="" alt="zemo_svaneti" title="zemo_svaneti" href="" coords="143,68,178,41,230,68" shape="poly">
    <area target="" alt="qvemo_svaneti" title="qvemo_svaneti" href="" coords="143,69,229,68,183,104" shape="poly">
    <area target="" alt="samegrelo" title="samegrelo" href="" coords="104,87,142,69,183,104,115,119" shape="poly">
    <area target="" alt="imereti" title="imereti" href="" coords="210,132,183,104,115,120" shape="poly">
    <area target="" alt="adjara_sanapiro" title="adjara_sanapiro" href="" coords="107,201,129,161,208,133" shape="poly">
    <area target="" alt="adjara_bakhmaro" title="adjara_bakhmaro" href="" coords="211,133,207,198,108,201" shape="poly">
    <area target="" alt="qvemo_qartli_1" title="qvemo_qartli_1" href="" coords="212,133,299,159,252,236" shape="poly">
    <area target="" alt="qvemo_qartli_2" title="qvemo_qartli_2" href="" coords="299,159,353,182,252,243,254,236" shape="poly">
    <area target="" alt="dusheti" title="dusheti" href="" coords="290,106,343,83,354,180" shape="poly">
    <area target="" alt="telavi" title="telavi" href="" coords="388,207,413,138,354,182" shape="poly">
    <area target="" alt="gurjaani" title="gurjaani" href="" coords="414,139,434,182,390,206" shape="poly">
    <area target="" alt="racha" title="racha" href="" coords="229,69,212,132,276,88" shape="poly">
</map>
            </div>
            <div class="info">
                <div class="info-title">
                     <h3 id="place">Vardzia</h3>
                </div>
               
                <div class="info-about">
                    <h4 class="decription">Detailed Description Of The Tour</h4>
                    <ul id="tour-time">
                        <li>08:00 Going to vardzia from Tbilisi</li>
                        <li>11:00  visiting the cave town Vardzia (walking, 1.2 km. One way, easy)</li>
                        <li>14:00  gpicnic</li>
                        <li>15:30  gvisiting Khertvisi fortress</li>
                        <li>17:00  gvisiting The Saghamo Lake</li>
                        <li>18:30  gvisiting Paravani Lake and Poka Monastery</li>
                        <li>20:00  goint back to Tbilisi</li>
                    </ul>
                    <div class="price">
                        <p id="price-title">Price: 
                        <span> 150</span> Gel</p>
                        <p id="price-person">&#43; Lunch (1 person) <span> 30</span> Gel <br>
                        &#43; Tickets (1 person) <span> 10</span> Gel
                        </p>
                        <div class="just-space"></div>
                    </div>
                    <p class="notLike">Dont't you like the tour or time?</p>
                    <p class="choose-yours">Choose yours <span >&#9660</span> </p>
                    
                </div>
            </div>
            
        </div>
    </div>

    </body>
</html>