<html>
    <body>
        
    <video id="video"  src="media/video/FallColorofNorthGeorgia.mp4" autoplay loop muted>
  
  Your browser does not support the video tag.
</video>

<div class="opacity"></div>


<div class="content content-about">
    <div class="sound">
        <img id="speaker" src="media/images/icon/speakerOff.png" alt="speaker">
    </div>
    <h2 class="title">Tours</h2>

    <div class="tours">
        <h3 class="tour-title">choose the duration of the trip<br> that best suits you  </h3>
        <div class="tour-container">
            <div class="tour-duration">
                <p class="duration">1<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">2<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">3<br>Day</p>
            </div>
            <div class="tour-duration">
                <p class="duration">1<br>Week</p>
            </div>
            <div class="tour-duration">
                <p class="duration">Custom</p>
            </div>
        </div>
    </div>

    <div class="choose-tour">
        <div class="choose-duration">
            <div class="back duration-circle">
                <p class="back-p">&#9664;</p>
            </div>
            <div class="duration-number duration-circle">
                <p class="duration-number-p">
                    Choose <br> Number  <br>
                    <span id="duration-number-arrow">&#9660</span>
                    
                </p>
            </div>
            <div class="duration-day duration-circle">
                <p class="duration-day-p">
                    <span id="duration-day-span">Day</span> <br>
                    <span class="week-top">Week</span><br>
                   
                </p>
            </div>
            <div class="go duration-circle">
                <p class="duration-circle-p">
                    GO
                </p>
            </div>
            <div class="numbers">
                <span class="numbers-number">1</span>
                <span class="numbers-number">2</span>
                <span class="numbers-number">3</span>
                <span class="numbers-number">4</span>
                <span class="numbers-number">5</span>
                <span class="numbers-number">6</span>
                <span class="numbers-number">7</span>
            </div>
        </div>

        <div class="tour-main">
            <div class="map">
                <img id="map" src="media/images/map.png" alt="map" usemap="#image-map">
                <!-- Image Map Generated by http://www.image-map.net/ -->


                <map name="image-map">
    <area target="" alt="zemo_svaneti" title="zemo_svaneti" href="" coords="143,68,178,41,230,68" shape="poly">
    <area target="" alt="qvemo_svaneti" title="qvemo_svaneti" href="" coords="143,69,229,68,183,104" shape="poly">
    <area target="" alt="samegrelo" title="samegrelo" href="" coords="104,87,142,69,183,104,115,119" shape="poly">
    <area target="" alt="imereti" title="imereti" href="" coords="210,132,183,104,115,120" shape="poly">
    <area target="" alt="adjara_sanapiro" title="adjara_sanapiro" href="" coords="107,201,129,161,208,133" shape="poly">
    <area target="" alt="adjara_bakhmaro" title="adjara_bakhmaro" href="" coords="211,133,207,198,108,201" shape="poly">
    <area target="" alt="qvemo_qartli_1" title="qvemo_qartli_1" href="" coords="212,133,299,159,252,236" shape="poly">
    <area target="" alt="qvemo_qartli_2" title="qvemo_qartli_2" href="" coords="299,159,353,182,252,243,254,236" shape="poly">
    <area target="" alt="dusheti" title="dusheti" href="" coords="290,106,343,83,354,180" shape="poly">
    <area target="" alt="telavi" title="telavi" href="" coords="388,207,413,138,354,182" shape="poly">
    <area target="" alt="gurjaani" title="gurjaani" href="" coords="414,139,434,182,390,206" shape="poly">
    <area target="" alt="racha" title="racha" href="" coords="229,69,212,132,276,88" shape="poly">
</map>
            </div>
            <div class="info">
                <div class="info-title">
                     <h3 id="place">Vardzia</h3>
                </div>
               
                <div class="info-about">
                    <h4 class="decription">Detailed Description Of The Tour</h4>
                    <ul>
                        <li>sadfsadfsd</li>
                        <li>asdfasdfsadf</li>
                        <li>adfasdfsad</li>
                        <li>adsfasdfasdf</li>
                        <li>asdfasdfas</li>
                        <li>adfasdfas</li>
                        <li>asdfasdfsdfsadf</li>
                    </ul>

                </div>
            </div>
            
        </div>
    </div>

    </body>
</html>